import process from "node:process";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { createPostgresDatabase } from "../src/server/database/pool";
import type { AppDatabase } from "../src/server/database/types";

/**
 * 此连接串只允许指向由 docker-compose.dev.yml 创建的可销毁 switch_test 数据库。
 * 测试拒绝缺失环境变量，避免开发者误把集成测试静默切换到 NAS、生产库或个人默认数据库。
 */
const connectionString = process.env.TEST_DATABASE_URL;
if (!connectionString) {
  throw new Error("必须显式设置 TEST_DATABASE_URL 才能运行 PostgreSQL 集成测试");
}

describe("PostgreSQL 连接池、事务与互斥锁", () => {
  let database: AppDatabase;

  beforeAll(async () => {
    database = createPostgresDatabase(connectionString);
    // migration_probe 只存在于一次性测试库；独立探针表让提交和回滚断言不依赖正式业务 schema。
    await database.query(`
      CREATE TABLE IF NOT EXISTS migration_probe (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        value TEXT NOT NULL
      )
    `);
  });

  beforeEach(async () => {
    // 每例清空并重置自增序列，确保前一测试的事务结果不会影响下一测试的行数和身份值。
    await database.query("TRUNCATE TABLE migration_probe RESTART IDENTITY");
  });

  afterAll(async () => {
    // 关闭主连接池是进程退出边界的一部分；正式表不在此删除，因为整个 Compose 数据目录本身就是一次性的。
    await database.close();
  });

  it("使用 PostgreSQL 参数绑定传递值并返回非空 rowCount", async () => {
    const inserted = await database.query<{ value: string }>(
      "INSERT INTO migration_probe (value) VALUES ($1) RETURNING value",
      ["parameter-bound"],
    );

    expect(inserted).toEqual({
      rows: [{ value: "parameter-bound" }],
      rowCount: 1,
    });
  });

  it("事务工作正常返回时提交全部语句", async () => {
    const value = await database.transaction(async (transaction) => {
      await transaction.query("INSERT INTO migration_probe (value) VALUES ($1)", ["committed"]);
      return "transaction-result";
    });

    const result = await database.query<{ value: string }>(
      "SELECT value FROM migration_probe ORDER BY id",
    );
    expect(value).toBe("transaction-result");
    expect(result.rows).toEqual([{ value: "committed" }]);
  });

  it("事务工作抛错时回滚全部语句", async () => {
    await expect(
      database.transaction(async (transaction) => {
        await transaction.query(
          "INSERT INTO migration_probe (value) VALUES ($1)",
          ["kept-only-on-commit"],
        );
        throw new Error("expected rollback");
      }),
    ).rejects.toThrow("expected rollback");

    const result = await database.query<{ count: string }>(
      "SELECT COUNT(*) AS count FROM migration_probe",
    );
    expect(result.rows[0].count).toBe("0");
  });

  it("成功取得 advisory lock 时在同一已检出连接上执行工作", async () => {
    const result = await database.withAdvisoryLock(8_602_727_001n, async (connection) => {
      const probe = await connection.query<{ locked: boolean }>("SELECT TRUE AS locked");
      return probe.rows[0].locked;
    });

    expect(result).toBe(true);
  });

  it("相同 advisory lock 已被占用时立即返回 undefined 而不排队", async () => {
    let releaseFirstLock!: () => void;
    let notifyFirstLockHeld!: () => void;
    const firstLockHeld = new Promise<void>((resolve) => {
      notifyFirstLockHeld = resolve;
    });
    const keepFirstLockHeld = new Promise<void>((resolve) => {
      releaseFirstLock = resolve;
    });

    const firstDatabase = createPostgresDatabase(connectionString);
    const secondDatabase = createPostgresDatabase(connectionString);
    try {
      const firstWork = firstDatabase.withAdvisoryLock(8_602_727_002n, async () => {
        notifyFirstLockHeld();
        await keepFirstLockHeld;
        return "first";
      });
      await firstLockHeld;

      await expect(
        secondDatabase.withAdvisoryLock(8_602_727_002n, async () => "second"),
      ).resolves.toBeUndefined();

      releaseFirstLock();
      await expect(firstWork).resolves.toBe("first");
    } finally {
      // 若断言失败也必须解除等待并关闭两个池，避免泄漏锁、客户端或让 Vitest 进程挂起。
      releaseFirstLock?.();
      await Promise.all([firstDatabase.close(), secondDatabase.close()]);
    }
  });

  it("close 后拒绝新查询并允许进程清理连接池资源", async () => {
    const closeProbe = createPostgresDatabase(connectionString);
    await closeProbe.query("SELECT 1");
    await closeProbe.close();

    await expect(closeProbe.query("SELECT 1")).rejects.toThrow();
  });
});
