import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import type { AppDatabase } from "../src/server/database/types";
import { createTestDatabase } from "./support/postgres";

describe("PostgreSQL 数据库基础契约", () => {
  let database: AppDatabase;

  beforeAll(async () => {
    database = createTestDatabase();
    // 探针表只存在于 TEST_DATABASE_URL 指定的可丢弃数据库，用于观察提交、回滚和参数绑定，绝不写入开发或 NAS 数据库。
    await database.query(`
      CREATE TABLE IF NOT EXISTS migration_probe (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        value TEXT NOT NULL
      )
    `);
  });

  beforeEach(async () => {
    // 每个用例从空表开始，避免自增主键和前一用例的提交结果影响事务边界判断。
    await database.query("TRUNCATE TABLE migration_probe RESTART IDENTITY");
  });

  afterAll(async () => {
    await database.close();
  });

  it("使用 PostgreSQL 参数占位符绑定值并返回非空行数", async () => {
    const inserted = await database.query<{ value: string }>(
      "INSERT INTO migration_probe (value) VALUES ($1) RETURNING value",
      ["bound-value"],
    );

    expect(inserted).toEqual({ rows: [{ value: "bound-value" }], rowCount: 1 });
  });

  it("事务工作成功时提交全部语句", async () => {
    await database.transaction(async (transaction) => {
      await transaction.query("INSERT INTO migration_probe (value) VALUES ($1)", ["committed"]);
      await transaction.query("INSERT INTO migration_probe (value) VALUES ($1)", ["also-committed"]);
    });

    const result = await database.query<{ count: string }>("SELECT COUNT(*) AS count FROM migration_probe");
    expect(result.rows[0].count).toBe("2");
  });

  it("事务工作抛错时回滚全部语句", async () => {
    await expect(database.transaction(async (transaction) => {
      await transaction.query("INSERT INTO migration_probe (value) VALUES ($1)", ["kept-only-on-commit"]);
      throw new Error("expected rollback");
    })).rejects.toThrow("expected rollback");

    const result = await database.query<{ count: string }>("SELECT COUNT(*) AS count FROM migration_probe");
    expect(result.rows[0].count).toBe("0");
  });

  it("无人持有会话锁时执行受保护工作并在结束后释放连接与锁", async () => {
    const value = await database.withAdvisoryLock(92_001n, async (connection) => {
      // 回调只能通过受限 executor 查询；成功得到常量证明锁已获取且原始 PoolClient 没有泄漏到测试或业务层。
      const result = await connection.query<{ locked: boolean }>("SELECT TRUE AS locked");
      return result.rows[0].locked;
    });

    expect(value).toBe(true);
    await expect(database.withAdvisoryLock(92_001n, async () => "reacquired")).resolves.toBe("reacquired");
  });

  it("同一 advisory key 发生竞争时立即返回 undefined 且不执行第二份工作", async () => {
    let releaseFirstLock!: () => void;
    const firstCanFinish = new Promise<void>((resolve) => {
      releaseFirstLock = resolve;
    });
    let firstHasLock!: () => void;
    const firstStarted = new Promise<void>((resolve) => {
      firstHasLock = resolve;
    });

    const first = database.withAdvisoryLock(92_003n, async () => {
      firstHasLock();
      await firstCanFinish;
      return "first";
    });
    await firstStarted;

    const contenderWork = vi.fn(async () => "second");
    await expect(database.withAdvisoryLock(92_003n, contenderWork)).resolves.toBeUndefined();
    expect(contenderWork).not.toHaveBeenCalled();

    releaseFirstLock();
    await expect(first).resolves.toBe("first");
  });
});

describe("PostgreSQL 连接池关闭", () => {
  it("close 等待连接池关闭，之后拒绝新的查询", async () => {
    const database = createTestDatabase();
    await database.query("SELECT 1");

    await database.close();

    await expect(database.query("SELECT 1")).rejects.toThrow();
  });
});
