-- 迁移历史按不可变文件名与 SHA-256 校验和记录；启动时任何已应用文件被修改都必须失败，禁止静默重写数据库事实。
CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  checksum TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 全局设置固定为单管理员单行；地区结构使用 JSONB 便于原样往返，但默认区属于启用区等业务关系仍必须由服务层白名单验证。
CREATE TABLE settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  enabled_regions_json JSONB NOT NULL,
  default_search_region TEXT NOT NULL,
  theme TEXT NOT NULL DEFAULT 'warm-card',
  timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai',
  daily_report_time TEXT NOT NULL DEFAULT '09:00',
  tax_state TEXT NOT NULL DEFAULT 'OR',
  price_history_retention TEXT NOT NULL DEFAULT 'forever',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

-- 游戏是跨地区商品的逻辑主档；规范化名称只对非空值唯一，既允许旧记录待补全，也阻止并发确认创建重复逻辑商品。
CREATE TABLE games (
  id TEXT PRIMARY KEY,
  name_zh TEXT NOT NULL,
  name_en TEXT NOT NULL,
  normalized_name TEXT,
  publisher TEXT,
  product_type TEXT NOT NULL,
  cover_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX games_normalized_name_unique
  ON games (normalized_name)
  WHERE normalized_name IS NOT NULL;

-- 地区商品保留官方商品 ID、URL 与匹配来源以审计价格来源；同一游戏每区唯一，enabled 使用原生 BOOLEAN 而非可混入其他整数的标记。
CREATE TABLE regional_products (
  id TEXT PRIMARY KEY,
  game_id TEXT NOT NULL REFERENCES games(id) ON DELETE RESTRICT,
  region_code TEXT NOT NULL,
  currency TEXT NOT NULL,
  official_product_id TEXT,
  product_url TEXT NOT NULL,
  match_source TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (game_id, region_code)
);

-- 订阅以 game_id 唯一并支持软停用；全局目标价继续保存人民币分整数，禁止浮点舍入改变命中通知边界。
CREATE TABLE subscriptions (
  id TEXT PRIMARY KEY,
  game_id TEXT NOT NULL REFERENCES games(id) ON DELETE RESTRICT,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  global_target_cny_fen INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (game_id)
);

-- 删除订阅时级联其地区选择属于明确的破坏性业务操作；地区商品仍受 RESTRICT 保护，不能因关系删除而丢失价格来源主档。
CREATE TABLE subscription_regions (
  subscription_id TEXT NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
  regional_product_id TEXT NOT NULL REFERENCES regional_products(id) ON DELETE RESTRICT,
  PRIMARY KEY (subscription_id, regional_product_id)
);

-- 单区目标价以当地货币最小单位整数保存；状态约束只允许 unmet/met，保证首次命中通知与价格回升重置具有确定状态机。
CREATE TABLE subscription_region_targets (
  subscription_id TEXT NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
  region_code TEXT NOT NULL,
  target_amount_minor INTEGER NOT NULL,
  target_state TEXT NOT NULL DEFAULT 'unmet' CHECK (target_state IN ('unmet', 'met')),
  PRIMARY KEY (subscription_id, region_code)
);

-- 价格快照只追加，金额与人民币换算均为整数最小单位；source、currency 与采集时间共同保留官方价格来源和汇率缺失时的可追溯性。
CREATE TABLE price_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regional_product_id TEXT NOT NULL REFERENCES regional_products(id) ON DELETE RESTRICT,
  amount_minor INTEGER NOT NULL,
  currency TEXT NOT NULL,
  cny_fen INTEGER,
  exchange_rate DOUBLE PRECISION,
  source TEXT NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 最新价、历史低价和保留任务按商品与 UTC 采集时刻访问；降序索引避免长期保留策略造成全表扫描。
CREATE INDEX idx_price_snapshots_product_captured
  ON price_snapshots (regional_product_id, captured_at DESC);

-- 汇率保留来源和 stale 标志，过期回退值不得伪装为当天成功抓取；同币种同采集时刻唯一，防止并发任务重复记录。
CREATE TABLE exchange_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  currency TEXT NOT NULL,
  cny_rate DOUBLE PRECISION NOT NULL,
  source TEXT NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL,
  is_stale BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (currency, captured_at)
);

-- 采集日志只保存脱敏摘要并按固定九十天策略清理；地区商品被安全删除后以 SET NULL 保留诊断事实，不能反向暴露或伪造来源。
CREATE TABLE fetch_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regional_product_id TEXT REFERENCES regional_products(id) ON DELETE SET NULL,
  source TEXT NOT NULL,
  status TEXT NOT NULL,
  duration_ms INTEGER,
  message TEXT,
  captured_at TIMESTAMPTZ NOT NULL
);

-- 捕获时间索引是九十天固定日志保留边界的执行基础，清理等于截止时刻的记录时无需扫描全部诊断历史。
CREATE INDEX idx_fetch_logs_captured_at ON fetch_logs (captured_at);

-- 健康状态与地区商品一一对应并随主档删除；连续失败和已通知布尔值共同防止每轮采集重复发送同一故障提醒。
CREATE TABLE regional_product_health (
  regional_product_id TEXT PRIMARY KEY REFERENCES regional_products(id) ON DELETE CASCADE,
  consecutive_failures INTEGER NOT NULL DEFAULT 0,
  last_success_at TIMESTAMPTZ,
  failure_notified BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 通知事件用 dedupe_key 原子预留唯一发送资格，避免重试、并发调度或分页投递重复通知；删除业务主档时 SET NULL 保留审计事件。
CREATE TABLE notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id TEXT REFERENCES subscriptions(id) ON DELETE SET NULL,
  regional_product_id TEXT REFERENCES regional_products(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  status TEXT NOT NULL,
  dedupe_key TEXT NOT NULL UNIQUE,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 单管理员认证表只允许 id=1；密码与恢复码仅存加盐派生材料，永不保存明文，恢复成功时间阻止同一恢复码重放。
CREATE TABLE admin_credentials (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  recovery_hash TEXT NOT NULL,
  recovery_salt TEXT NOT NULL,
  recovery_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL
);

-- 会话只保存 Cookie 原始令牌的 SHA-256 摘要；唯一 token_hash 防止摘要复用，revoked_at 支持退出和密码重置后的明确失效审计。
CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ
);

-- 登录失败计数固定为单管理员一行；locked_until 使用 UTC 时区时间，跨进程执行连续五次失败锁定时不会受 NAS 本地时区影响。
CREATE TABLE login_attempts (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  failed_count INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ
);

-- 立即手动刷新只保留最近请求时刻以协调跨标签页状态；不保存管理员会话、浏览器标识、价格响应或任何 Telegram 凭据。
CREATE TABLE manual_refresh_requests (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  requested_at TIMESTAMPTZ NOT NULL
);
