-- 迁移账本保存不可变文件名、精确字节 SHA-256 与应用时间；启动器在专用 advisory lock 下校验，
-- 任何历史迁移被改写都必须停止启动，不能在未知结构上继续处理认证、价格或通知。
CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  checksum TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 全局设置是单管理员单例。enabled_regions_json 使用 JSONB 保存结构化地区数组，
-- 地区白名单、默认区必须属于启用区等跨字段规则仍由服务层验证，数据库只保证单例与非空基础约束。
CREATE TABLE settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  enabled_regions_json JSONB NOT NULL,
  default_search_region TEXT NOT NULL,
  theme TEXT NOT NULL DEFAULT 'warm-card',
  timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai',
  daily_report_time TEXT NOT NULL DEFAULT '09:00',
  tax_state TEXT NOT NULL DEFAULT 'OR',
  price_history_retention TEXT NOT NULL DEFAULT 'forever',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

-- games 保存可跨五区归并的逻辑商品；标题、发行商和类型共同防止把本体、DLC、升级包错误合并。
-- normalized_name 允许旧/待确认记录为空，非空身份由后面的部分唯一索引提供并发去重。
CREATE TABLE games (
  id TEXT PRIMARY KEY,
  name_zh TEXT NOT NULL,
  name_en TEXT NOT NULL,
  normalized_name TEXT,
  publisher TEXT,
  product_type TEXT NOT NULL,
  cover_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 每个逻辑商品在每区只能映射一个地区商品。官方价格 ID、官方 URL 和 match_source 共同记录价格来源，
-- 便于审计自动/人工确认；enabled 使用原生 BOOLEAN，禁止以 SQLite 的 0/1 文本语义混用。
-- game 删除使用 RESTRICT，防止仍有地区价格来源时破坏历史追溯链。
CREATE TABLE regional_products (
  id TEXT PRIMARY KEY,
  game_id TEXT NOT NULL REFERENCES games(id) ON DELETE RESTRICT,
  region_code TEXT NOT NULL,
  currency TEXT NOT NULL,
  official_product_id TEXT,
  product_url TEXT NOT NULL,
  match_source TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (game_id, region_code)
);

-- 订阅以 game_id 唯一并支持软停用，避免普通取消操作丢失价格历史。
-- 全局目标价继续使用人民币分整数，绝不用浮点数保存货币；非负等业务校验由现有服务规则负责。
CREATE TABLE subscriptions (
  id TEXT PRIMARY KEY,
  game_id TEXT NOT NULL REFERENCES games(id) ON DELETE RESTRICT,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  global_target_cny_fen INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (game_id)
);

-- 多对多关系记录管理员实际选择的地区商品。删除订阅可级联清理纯关系记录；
-- 地区商品使用 RESTRICT，永久删除必须先按业务流程验证并显式清理依赖，不能由级联误删共享来源。
CREATE TABLE subscription_regions (
  subscription_id TEXT NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
  regional_product_id TEXT NOT NULL REFERENCES regional_products(id) ON DELETE RESTRICT,
  PRIMARY KEY (subscription_id, regional_product_id)
);

-- 单区目标价以当地货币最小单位整数保存，优先于全局人民币目标价。
-- target_state 只允许 unmet/met，使“首次命中通知、价格回升重置”的去重状态不能写入未知值。
CREATE TABLE subscription_region_targets (
  subscription_id TEXT NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
  region_code TEXT NOT NULL,
  target_amount_minor INTEGER NOT NULL,
  target_state TEXT NOT NULL DEFAULT 'unmet' CHECK (target_state IN ('unmet', 'met')),
  PRIMARY KEY (subscription_id, region_code)
);

-- 价格快照只追加，原币金额和人民币分均为整数最小单位；exchange_rate 可空，
-- 表示官方本币报价成功但汇率暂不可得。来源、币种和捕获时间保留价格溯源证据。
-- 地区商品删除使用 RESTRICT，永久删除流程必须显式决定是否清除历史，禁止数据库级联静默丢失价格曲线。
CREATE TABLE price_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regional_product_id TEXT NOT NULL REFERENCES regional_products(id) ON DELETE RESTRICT,
  amount_minor INTEGER NOT NULL,
  currency TEXT NOT NULL,
  cny_fen INTEGER,
  exchange_rate DOUBLE PRECISION,
  source TEXT NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 最新价格与历史曲线都按地区商品和捕获时间读取；降序复合索引避免保留期较长时扫描全部快照。
CREATE INDEX idx_price_snapshots_product_captured
  ON price_snapshots (regional_product_id, captured_at DESC);

-- 每日汇率单独保存来源和捕获时间，is_stale 明确区分当日成功值与最近成功值回退，
-- 防止旧汇率被伪装成当日中间价；同一币种同一捕获时刻只允许一条审计记录。
CREATE TABLE exchange_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  currency TEXT NOT NULL,
  cny_rate DOUBLE PRECISION NOT NULL,
  source TEXT NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL,
  is_stale BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (currency, captured_at)
);

-- 采集日志只保存来源、状态和脱敏错误摘要，不得写入会话、Telegram 凭据或完整供应商响应。
-- 日志固定保留 90 天；地区商品永久删除时 SET NULL 保留诊断证据，但解除已删除业务主档引用。
CREATE TABLE fetch_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regional_product_id TEXT REFERENCES regional_products(id) ON DELETE SET NULL,
  source TEXT NOT NULL,
  status TEXT NOT NULL,
  duration_ms INTEGER,
  message TEXT,
  captured_at TIMESTAMPTZ NOT NULL
);

-- 捕获时间索引服务固定 90 天日志保留任务和最近异常查询，避免维护任务扫描整表。
CREATE INDEX idx_fetch_logs_captured_at ON fetch_logs (captured_at);

-- 连续失败数、最近成功时间和已通知标志跨调度轮次保存，支持三次失败/恢复提醒去重。
-- 健康状态完全依附地区商品，商品按受控永久删除流程移除时可安全级联清理。
CREATE TABLE regional_product_health (
  regional_product_id TEXT PRIMARY KEY REFERENCES regional_products(id) ON DELETE CASCADE,
  consecutive_failures INTEGER NOT NULL DEFAULT 0,
  last_success_at TIMESTAMPTZ,
  failure_notified BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- dedupe_key 唯一约束为重试、并发调度和分页发送提供原子通知资格，避免同一价格/健康事件重复推送。
-- 订阅或地区商品永久删除时仅 SET NULL，保留通知状态审计；sent_at 只能在 Telegram 明确成功后由服务事务更新。
CREATE TABLE notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id TEXT REFERENCES subscriptions(id) ON DELETE SET NULL,
  regional_product_id TEXT REFERENCES regional_products(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  status TEXT NOT NULL,
  dedupe_key TEXT NOT NULL UNIQUE,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 单管理员认证材料只允许 id=1。密码和恢复码仅保存加盐派生值，绝不保存明文；
-- recovery_used_at 一旦写入即表示恢复码已消费，防止同一恢复凭据重放夺取账户。
CREATE TABLE admin_credentials (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  recovery_hash TEXT NOT NULL,
  recovery_salt TEXT NOT NULL,
  recovery_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL
);

-- Cookie 原始会话令牌不入库，只保存 SHA-256 摘要；唯一约束禁止摘要复用。
-- expires_at 和 revoked_at 使用 TIMESTAMPTZ，支持单设备退出及密码重置事务中的全会话撤销。
CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ
);

-- 个人部署只有一个管理员，失败次数按 id=1 聚合；locked_until 支持连续五次失败后的临时锁定。
-- 该表不记录尝试密码、IP 原文或会话令牌，避免认证日志扩大敏感数据面。
CREATE TABLE login_attempts (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  failed_count INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ
);

-- 立即手动刷新同步执行后，本单行只记录最近请求时刻，供跨标签页展示和后续业务规则使用。
-- 它不保存管理员、商品、会话、价格或供应商响应；id=1 防止并发请求产生多行不一致状态。
CREATE TABLE manual_refresh_requests (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  requested_at TIMESTAMPTZ NOT NULL
);

-- 仅对非空规范化身份建立唯一索引：旧记录可暂时为空，新确认流程则在数据库层并发安全地拒绝重复游戏与订阅。
CREATE UNIQUE INDEX games_normalized_name_unique
  ON games (normalized_name)
  WHERE normalized_name IS NOT NULL;
